spring:
    profiles:
        active: dev
    data:
        mongodb:
            database: "IMS"
            port: 27017
            host: localhost

cors:
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"

application:
    security:
        jwt:
            expiration: 86400000
            refresh-token:
                expiration: 604800000