spring:
    data:
        mongodb:
            uri: ${MONGODB_URI}

cors:
    allowed-origins: "https://inventory-management-system-nu-umber.vercel.app"

application:
    security:
        jwt:
            secret-key: ${JWT_SECRET_KEY}